// SPDX-License-Identifier: Apache-2.0

import { Driver } from '../connection/drivers';
import type { ColumnType } from './types';

const POSTGRES_TYPES: ColumnType[] = [
  { name: 'SERIAL', category: 'integer', isAutoIncrement: true },
  { name: 'BIGSERIAL', category: 'integer', isAutoIncrement: true },
  { name: 'SMALLINT', category: 'integer' },
  { name: 'INTEGER', category: 'integer' },
  { name: 'BIGINT', category: 'integer' },
  { name: 'REAL', category: 'float' },
  { name: 'DOUBLE PRECISION', category: 'float' },
  { name: 'NUMERIC', category: 'float', hasPrecision: true },
  { name: 'DECIMAL', category: 'float', hasPrecision: true },
  { name: 'VARCHAR', category: 'string', hasLength: true },
  { name: 'CHAR', category: 'string', hasLength: true },
  { name: 'TEXT', category: 'text' },
  { name: 'DATE', category: 'date' },
  { name: 'TIME', category: 'date' },
  { name: 'TIMESTAMP', category: 'date' },
  { name: 'TIMESTAMPTZ', category: 'date' },
  { name: 'BOOLEAN', category: 'boolean' },
  { name: 'UUID', category: 'other' },
  { name: 'BYTEA', category: 'binary' },
  { name: 'JSON', category: 'json' },
  { name: 'JSONB', category: 'json' },
];

const MYSQL_TYPES: ColumnType[] = [
  { name: 'TINYINT', category: 'integer' },
  { name: 'SMALLINT', category: 'integer' },
  { name: 'MEDIUMINT', category: 'integer' },
  { name: 'INT', category: 'integer' },
  { name: 'BIGINT', category: 'integer' },
  { name: 'FLOAT', category: 'float' },
  { name: 'DOUBLE', category: 'float' },
  { name: 'DECIMAL', category: 'float', hasPrecision: true },
  { name: 'VARCHAR', category: 'string', hasLength: true },
  { name: 'CHAR', category: 'string', hasLength: true },
  { name: 'TEXT', category: 'text' },
  { name: 'MEDIUMTEXT', category: 'text' },
  { name: 'LONGTEXT', category: 'text' },
  { name: 'DATE', category: 'date' },
  { name: 'TIME', category: 'date' },
  { name: 'DATETIME', category: 'date' },
  { name: 'TIMESTAMP', category: 'date' },
  { name: 'BOOLEAN', category: 'boolean' },
  { name: 'BLOB', category: 'binary' },
  { name: 'JSON', category: 'json' },
];

const SQLITE_TYPES: ColumnType[] = [
  { name: 'INTEGER', category: 'integer' },
  { name: 'INT', category: 'integer' },
  { name: 'BIGINT', category: 'integer' },
  { name: 'SMALLINT', category: 'integer' },
  { name: 'TINYINT', category: 'integer' },
  { name: 'REAL', category: 'float' },
  { name: 'DOUBLE', category: 'float' },
  { name: 'FLOAT', category: 'float' },
  { name: 'NUMERIC', category: 'float', hasPrecision: true },
  { name: 'DECIMAL', category: 'float', hasPrecision: true },
  { name: 'TEXT', category: 'text' },
  { name: 'VARCHAR', category: 'string', hasLength: true },
  { name: 'CHAR', category: 'string', hasLength: true },
  { name: 'CLOB', category: 'text' },
  { name: 'DATE', category: 'date' },
  { name: 'DATETIME', category: 'date' },
  { name: 'TIMESTAMP', category: 'date' },
  { name: 'BOOLEAN', category: 'boolean' },
  { name: 'BLOB', category: 'binary' },
];

const DUCKDB_TYPES: ColumnType[] = [
  { name: 'TINYINT', category: 'integer' },
  { name: 'SMALLINT', category: 'integer' },
  { name: 'INTEGER', category: 'integer' },
  { name: 'BIGINT', category: 'integer' },
  { name: 'HUGEINT', category: 'integer' },
  { name: 'UTINYINT', category: 'integer' },
  { name: 'USMALLINT', category: 'integer' },
  { name: 'UINTEGER', category: 'integer' },
  { name: 'UBIGINT', category: 'integer' },
  { name: 'UHUGEINT', category: 'integer' },
  { name: 'BIGNUM', category: 'integer' },
  { name: 'FLOAT', category: 'float' },
  { name: 'DOUBLE', category: 'float' },
  { name: 'DECIMAL', category: 'float', hasPrecision: true },
  { name: 'VARCHAR', category: 'string', hasLength: true },
  { name: 'TEXT', category: 'text' },
  { name: 'DATE', category: 'date' },
  { name: 'TIME', category: 'date' },
  { name: 'TIMETZ', category: 'date' },
  { name: 'TIMESTAMP', category: 'date' },
  { name: 'TIMESTAMP_S', category: 'date' },
  { name: 'TIMESTAMP_MS', category: 'date' },
  { name: 'TIMESTAMP_NS', category: 'date' },
  { name: 'TIMESTAMPTZ', category: 'date' },
  { name: 'INTERVAL', category: 'date' },
  { name: 'BOOLEAN', category: 'boolean' },
  { name: 'UUID', category: 'other' },
  { name: 'BIT', category: 'binary' },
  { name: 'BLOB', category: 'binary' },
  { name: 'JSON', category: 'json' },
];

const CLICKHOUSE_TYPES: ColumnType[] = [
  { name: 'Int8', category: 'integer' },
  { name: 'Int16', category: 'integer' },
  { name: 'Int32', category: 'integer' },
  { name: 'Int64', category: 'integer' },
  { name: 'Int128', category: 'integer' },
  { name: 'UInt8', category: 'integer' },
  { name: 'UInt16', category: 'integer' },
  { name: 'UInt32', category: 'integer' },
  { name: 'UInt64', category: 'integer' },
  { name: 'Float32', category: 'float' },
  { name: 'Float64', category: 'float' },
  { name: 'Decimal', category: 'float', hasPrecision: true },
  { name: 'String', category: 'text' },
  { name: 'FixedString', category: 'string', hasLength: true },
  { name: 'Date', category: 'date' },
  { name: 'Date32', category: 'date' },
  { name: 'DateTime', category: 'date' },
  { name: 'DateTime64', category: 'date', hasPrecision: true },
  { name: 'Bool', category: 'boolean' },
  { name: 'UUID', category: 'other' },
  { name: 'Enum8', category: 'other' },
  { name: 'Enum16', category: 'other' },
  { name: 'JSON', category: 'json' },
  { name: 'Array', category: 'other' },
  { name: 'Tuple', category: 'other' },
  { name: 'Map', category: 'other' },
  { name: 'IPv4', category: 'other' },
  { name: 'IPv6', category: 'other' },
];

const SQLSERVER_TYPES: ColumnType[] = [
  { name: 'TINYINT', category: 'integer' },
  { name: 'SMALLINT', category: 'integer' },
  { name: 'INT', category: 'integer' },
  { name: 'BIGINT', category: 'integer' },
  { name: 'FLOAT', category: 'float' },
  { name: 'REAL', category: 'float' },
  { name: 'DECIMAL', category: 'float', hasPrecision: true },
  { name: 'NUMERIC', category: 'float', hasPrecision: true },
  { name: 'MONEY', category: 'float' },
  { name: 'SMALLMONEY', category: 'float' },
  { name: 'VARCHAR', category: 'string', hasLength: true },
  { name: 'NVARCHAR', category: 'string', hasLength: true },
  { name: 'CHAR', category: 'string', hasLength: true },
  { name: 'NCHAR', category: 'string', hasLength: true },
  { name: 'TEXT', category: 'text' },
  { name: 'NTEXT', category: 'text' },
  { name: 'DATE', category: 'date' },
  { name: 'TIME', category: 'date' },
  { name: 'DATETIME', category: 'date' },
  { name: 'DATETIME2', category: 'date' },
  { name: 'SMALLDATETIME', category: 'date' },
  { name: 'DATETIMEOFFSET', category: 'date' },
  { name: 'BIT', category: 'boolean' },
  { name: 'UNIQUEIDENTIFIER', category: 'other' },
  { name: 'VARBINARY', category: 'binary', hasLength: true },
  { name: 'BINARY', category: 'binary', hasLength: true },
  { name: 'IMAGE', category: 'binary' },
  { name: 'XML', category: 'other' },
];

export const COLUMN_TYPES: Record<Driver, ColumnType[]> = {
  [Driver.Cassandra]: [],
  [Driver.ScyllaDb]: [],
  [Driver.Snowflake]: [],
  [Driver.BigQuery]: [],
  [Driver.Postgres]: POSTGRES_TYPES,
  [Driver.Mysql]: MYSQL_TYPES,
  [Driver.Mongodb]: [],
  [Driver.DocumentDb]: [],
  [Driver.Redis]: [],
  [Driver.Valkey]: [],
  [Driver.Dragonfly]: [],
  [Driver.KeyDb]: [],
  [Driver.Garnet]: [],
  [Driver.Sqlite]: SQLITE_TYPES,
  [Driver.Duckdb]: DUCKDB_TYPES,
  [Driver.Motherduck]: DUCKDB_TYPES,
  [Driver.SqlServer]: SQLSERVER_TYPES,
  [Driver.AzureSql]: SQLSERVER_TYPES,
  [Driver.Synapse]: SQLSERVER_TYPES,
  [Driver.Cockroachdb]: POSTGRES_TYPES,
  [Driver.Mariadb]: MYSQL_TYPES,
  [Driver.PlanetScale]: MYSQL_TYPES,
  [Driver.TiDb]: MYSQL_TYPES,
  [Driver.StarRocks]: MYSQL_TYPES,
  [Driver.Doris]: MYSQL_TYPES,
  [Driver.SingleStore]: MYSQL_TYPES,
  [Driver.Supabase]: POSTGRES_TYPES,
  [Driver.Neon]: POSTGRES_TYPES,
  [Driver.Timescaledb]: POSTGRES_TYPES,
  [Driver.YugabyteDb]: POSTGRES_TYPES,
  [Driver.Clickhouse]: CLICKHOUSE_TYPES,
  [Driver.Elasticsearch]: [],
  [Driver.OpenSearch]: [],
};

export function getColumnTypes(driver: Driver): ColumnType[] {
  return COLUMN_TYPES[driver] || [];
}

/**
 * Whether the visual table builder has a type palette for this driver. An empty
 * palette means the engine's DDL is not modelled here, so offering "create
 * table" would open a dialog with nothing to choose from.
 */
export function supportsVisualDdl(driver: Driver | string): boolean {
  return (COLUMN_TYPES[driver as Driver]?.length ?? 0) > 0;
}
